trigger: none
pr: none

pool: azsdk-pool

variables:
  Codeql.SkipTaskAutoInjection: true

steps:
  - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
    parameters:
      Paths:
        - "eng"

  - script: echo "hello world"
    displayName: Print hello world
