trigger: none
pr: none

pool: azsdk-pool

variables:
  Codeql.SkipTaskAutoInjection: true
  skipComponentGovernanceDetection: true

steps:
  - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml

  - script: echo "hello world"
    displayName: Print hello world
